# USERS
GET http://localhost:4000/api/users/get

POST http://localhost:4000/api/users/register
Content-Type: application/json

{
    "email":"bob@bob",
    "username":"bob",
    "password":"bob"
}

POST http://localhost:4000/api/users/register
Content-Type: application/json

{
    "username":"jim",
    "password":"jim"
}


POST http://localhost:4000/api/users/login
Content-Type: application/json

{
    "email":"bob@bob",
    "password":"bob"
}



GET http://localhost:4000/api/users/validate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvYkBib2IiLCJpYXQiOjE2MzI4MzM5NzQsImV4cCI6MzI2NjAyNzk0OCwiaXNzIjoiaXNzdWVyIn0.cIdB_pQlBMFFB_BPVlLQs-Uk2Sxy-QAHTs3irB9Swsg

DELETE http://localhost:4000/api/users/delete


# CELLS

GET http://localhost:4000/api/cells/get

POST http://localhost:4000/api/cells/post
Content-Type: application/json

{
    "content":"console.log(1);",
    "type":"javascript"
}

POST http://localhost:4000/api/cells/post
Content-Type: application/json

{
    "content":"#header2",
    "type":"markdown"
}


PUT http://localhost:4000/api/cells/put
Content-Type: application/json

{
    "id":"614c7e01744341a407c4a6720",
    "content":"##header 2"
}


DELETE http://localhost:4000/api/cells/delete




